apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-digd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-digd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-digd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-digd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-digd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pxop-tenant/rhtap-demo-app/hacbs-test-project-digd@sha256:db50f59ebfccb2af9585ac5c770fd79fca67e5c01ffc6619fd44f5e81bf93f31
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
